// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_RED    Color = 0
	Color_GREEN  Color = 1
	Color_BLUE   Color = 2
	Color_YELLOW Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "RED",
		1: "GREEN",
		2: "BLUE",
		3: "YELLOW",
	}
	Color_value = map[string]int32{
		"RED":    0,
		"GREEN":  1,
		"BLUE":   2,
		"YELLOW": 3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

type ScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Value    int32                  `protobuf:"varint,1,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    int64                  `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint32Value   uint32                 `protobuf:"varint,3,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value   uint64                 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Sint32Value   int32                  `protobuf:"zigzag32,5,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"` //有符号 32 位整数（优化）,负数编码效率更高
	Sint64Value   int64                  `protobuf:"zigzag64,6,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Fixed32Value  uint32                 `protobuf:"fixed32,7,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"` //无符号 32 位整数（固定）,始终占 4 字节，大数值效率更高
	Fixed64Value  uint64                 `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Sfixed32Value int32                  `protobuf:"fixed32,9,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"` //有符号 32 位整数（固定）	始终占 4 字节
	Sfixed64Value int64                  `protobuf:"fixed64,10,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	FloatValue    float32                `protobuf:"fixed32,11,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue   float64                `protobuf:"fixed64,12,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	BoolValue     bool                   `protobuf:"varint,13,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue   string                 `protobuf:"bytes,14,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    []byte                 `protobuf:"bytes,15,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	mi := &file_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarTypes) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *ScalarTypes) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *ScalarTypes) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *ScalarTypes) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *ScalarTypes) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *ScalarTypes) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *ScalarTypes) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *ScalarTypes) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *ScalarTypes) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *ScalarTypes) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *ScalarTypes) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *ScalarTypes) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *ScalarTypes) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *ScalarTypes) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ScalarTypes) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

type InnerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerMessage) Reset() {
	*x = InnerMessage{}
	mi := &file_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMessage) ProtoMessage() {}

func (x *InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMessage.ProtoReflect.Descriptor instead.
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *InnerMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 复合类型
type ComplexTypes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	InnerMessage  *InnerMessage           `protobuf:"bytes,1,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
	Color         Color                   `protobuf:"varint,2,opt,name=color,proto3,enum=Color" json:"color,omitempty"` //枚举
	Names         []string                `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`             //字符串数组
	Numbers       []int32                 `protobuf:"varint,4,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	MapValue      map[string]int32        `protobuf:"bytes,5,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapMessage    map[int32]*InnerMessage `protobuf:"bytes,6,rep,name=map_message,json=mapMessage,proto3" json:"map_message,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexTypes) Reset() {
	*x = ComplexTypes{}
	mi := &file_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexTypes) ProtoMessage() {}

func (x *ComplexTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexTypes.ProtoReflect.Descriptor instead.
func (*ComplexTypes) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *ComplexTypes) GetInnerMessage() *InnerMessage {
	if x != nil {
		return x.InnerMessage
	}
	return nil
}

func (x *ComplexTypes) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_RED
}

func (x *ComplexTypes) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ComplexTypes) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *ComplexTypes) GetMapValue() map[string]int32 {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *ComplexTypes) GetMapMessage() map[int32]*InnerMessage {
	if x != nil {
		return x.MapMessage
	}
	return nil
}

type SpecialTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Empty         *emptypb.Empty         `protobuf:"bytes,3,opt,name=empty,proto3" json:"empty,omitempty"`
	Dynamic       *structpb.Struct       `protobuf:"bytes,4,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialTypes) Reset() {
	*x = SpecialTypes{}
	mi := &file_proto_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialTypes) ProtoMessage() {}

func (x *SpecialTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialTypes.ProtoReflect.Descriptor instead.
func (*SpecialTypes) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *SpecialTypes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SpecialTypes) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *SpecialTypes) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

func (x *SpecialTypes) GetDynamic() *structpb.Struct {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

// 包装类型示例,对应的值可为空
type WrapperTypes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Int32Value    *wrapperspb.Int32Value  `protobuf:"bytes,1,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    *wrapperspb.Int64Value  `protobuf:"bytes,2,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint32Value   *wrapperspb.UInt32Value `protobuf:"bytes,3,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value   *wrapperspb.UInt64Value `protobuf:"bytes,4,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	FloatValue    *wrapperspb.FloatValue  `protobuf:"bytes,5,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue   *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	BoolValue     *wrapperspb.BoolValue   `protobuf:"bytes,7,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    *wrapperspb.BytesValue  `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperTypes) Reset() {
	*x = WrapperTypes{}
	mi := &file_proto_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperTypes) ProtoMessage() {}

func (x *WrapperTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperTypes.ProtoReflect.Descriptor instead.
func (*WrapperTypes) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *WrapperTypes) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *WrapperTypes) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *WrapperTypes) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *WrapperTypes) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *WrapperTypes) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *WrapperTypes) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *WrapperTypes) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *WrapperTypes) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *WrapperTypes) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

// 综合示例
type AllTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scalars       *ScalarTypes           `protobuf:"bytes,1,opt,name=scalars,proto3" json:"scalars,omitempty"`
	Complex       *ComplexTypes          `protobuf:"bytes,2,opt,name=complex,proto3" json:"complex,omitempty"`
	Special       *SpecialTypes          `protobuf:"bytes,3,opt,name=special,proto3" json:"special,omitempty"`
	Wrappers      *WrapperTypes          `protobuf:"bytes,4,opt,name=wrappers,proto3" json:"wrappers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypes) Reset() {
	*x = AllTypes{}
	mi := &file_proto_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypes) ProtoMessage() {}

func (x *AllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypes.ProtoReflect.Descriptor instead.
func (*AllTypes) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{5}
}

func (x *AllTypes) GetScalars() *ScalarTypes {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *AllTypes) GetComplex() *ComplexTypes {
	if x != nil {
		return x.Complex
	}
	return nil
}

func (x *AllTypes) GetSpecial() *SpecialTypes {
	if x != nil {
		return x.Special
	}
	return nil
}

func (x *AllTypes) GetWrappers() *WrapperTypes {
	if x != nil {
		return x.Wrappers
	}
	return nil
}

var File_proto_types_proto protoreflect.FileDescriptor

const file_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x11proto/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9a\x04\n" +
	"\vScalarTypes\x12\x1f\n" +
	"\vint32_value\x18\x01 \x01(\x05R\n" +
	"int32Value\x12\x1f\n" +
	"\vint64_value\x18\x02 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint32_value\x18\x03 \x01(\rR\vuint32Value\x12!\n" +
	"\fuint64_value\x18\x04 \x01(\x04R\vuint64Value\x12!\n" +
	"\fsint32_value\x18\x05 \x01(\x11R\vsint32Value\x12!\n" +
	"\fsint64_value\x18\x06 \x01(\x12R\vsint64Value\x12#\n" +
	"\rfixed32_value\x18\a \x01(\aR\ffixed32Value\x12#\n" +
	"\rfixed64_value\x18\b \x01(\x06R\ffixed64Value\x12%\n" +
	"\x0esfixed32_value\x18\t \x01(\x0fR\rsfixed32Value\x12%\n" +
	"\x0esfixed64_value\x18\n" +
	" \x01(\x10R\rsfixed64Value\x12\x1f\n" +
	"\vfloat_value\x18\v \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\f \x01(\x01R\vdoubleValue\x12\x1d\n" +
	"\n" +
	"bool_value\x18\r \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\x0e \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x0f \x01(\fR\n" +
	"bytesValue\"\"\n" +
	"\fInnerMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x95\x03\n" +
	"\fComplexTypes\x122\n" +
	"\rinner_message\x18\x01 \x01(\v2\r.InnerMessageR\finnerMessage\x12\x1c\n" +
	"\x05color\x18\x02 \x01(\x0e2\x06.ColorR\x05color\x12\x14\n" +
	"\x05names\x18\x03 \x03(\tR\x05names\x12\x18\n" +
	"\anumbers\x18\x04 \x03(\x05R\anumbers\x128\n" +
	"\tmap_value\x18\x05 \x03(\v2\x1b.ComplexTypes.MapValueEntryR\bmapValue\x12>\n" +
	"\vmap_message\x18\x06 \x03(\v2\x1d.ComplexTypes.MapMessageEntryR\n" +
	"mapMessage\x1a;\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aL\n" +
	"\x0fMapMessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.InnerMessageR\x05value:\x028\x01\"\xe0\x01\n" +
	"\fSpecialTypes\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12,\n" +
	"\x05empty\x18\x03 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\x121\n" +
	"\adynamic\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adynamic\"\xc5\x04\n" +
	"\fWrapperTypes\x12<\n" +
	"\vint32_value\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12<\n" +
	"\vint64_value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x12?\n" +
	"\fuint32_value\x18\x03 \x01(\v2\x1c.google.protobuf.UInt32ValueR\vuint32Value\x12?\n" +
	"\fuint64_value\x18\x04 \x01(\v2\x1c.google.protobuf.UInt64ValueR\vuint64Value\x12<\n" +
	"\vfloat_value\x18\x05 \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"floatValue\x12?\n" +
	"\fdouble_value\x18\x06 \x01(\v2\x1c.google.protobuf.DoubleValueR\vdoubleValue\x129\n" +
	"\n" +
	"bool_value\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12?\n" +
	"\fstring_value\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12<\n" +
	"\vbytes_value\x18\t \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValue\"\xaf\x01\n" +
	"\bAllTypes\x12&\n" +
	"\ascalars\x18\x01 \x01(\v2\f.ScalarTypesR\ascalars\x12'\n" +
	"\acomplex\x18\x02 \x01(\v2\r.ComplexTypesR\acomplex\x12'\n" +
	"\aspecial\x18\x03 \x01(\v2\r.SpecialTypesR\aspecial\x12)\n" +
	"\bwrappers\x18\x04 \x01(\v2\r.WrapperTypesR\bwrappers*1\n" +
	"\x05Color\x12\a\n" +
	"\x03RED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\b\n" +
	"\x04BLUE\x10\x02\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x0324\n" +
	"\fTypesService\x12$\n" +
	"\fTestAllTypes\x12\t.AllTypes\x1a\t.AllTypesB\tZ\a./pb;pbb\x06proto3"

var (
	file_proto_types_proto_rawDescOnce sync.Once
	file_proto_types_proto_rawDescData []byte
)

func file_proto_types_proto_rawDescGZIP() []byte {
	file_proto_types_proto_rawDescOnce.Do(func() {
		file_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)))
	})
	return file_proto_types_proto_rawDescData
}

var file_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_types_proto_goTypes = []any{
	(Color)(0),                     // 0: Color
	(*ScalarTypes)(nil),            // 1: ScalarTypes
	(*InnerMessage)(nil),           // 2: InnerMessage
	(*ComplexTypes)(nil),           // 3: ComplexTypes
	(*SpecialTypes)(nil),           // 4: SpecialTypes
	(*WrapperTypes)(nil),           // 5: WrapperTypes
	(*AllTypes)(nil),               // 6: AllTypes
	nil,                            // 7: ComplexTypes.MapValueEntry
	nil,                            // 8: ComplexTypes.MapMessageEntry
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 10: google.protobuf.Duration
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
	(*wrapperspb.Int32Value)(nil),  // 13: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 14: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 15: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 16: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 17: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 18: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),   // 19: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 20: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 21: google.protobuf.BytesValue
}
var file_proto_types_proto_depIdxs = []int32{
	2,  // 0: ComplexTypes.inner_message:type_name -> InnerMessage
	0,  // 1: ComplexTypes.color:type_name -> Color
	7,  // 2: ComplexTypes.map_value:type_name -> ComplexTypes.MapValueEntry
	8,  // 3: ComplexTypes.map_message:type_name -> ComplexTypes.MapMessageEntry
	9,  // 4: SpecialTypes.timestamp:type_name -> google.protobuf.Timestamp
	10, // 5: SpecialTypes.duration:type_name -> google.protobuf.Duration
	11, // 6: SpecialTypes.empty:type_name -> google.protobuf.Empty
	12, // 7: SpecialTypes.dynamic:type_name -> google.protobuf.Struct
	13, // 8: WrapperTypes.int32_value:type_name -> google.protobuf.Int32Value
	14, // 9: WrapperTypes.int64_value:type_name -> google.protobuf.Int64Value
	15, // 10: WrapperTypes.uint32_value:type_name -> google.protobuf.UInt32Value
	16, // 11: WrapperTypes.uint64_value:type_name -> google.protobuf.UInt64Value
	17, // 12: WrapperTypes.float_value:type_name -> google.protobuf.FloatValue
	18, // 13: WrapperTypes.double_value:type_name -> google.protobuf.DoubleValue
	19, // 14: WrapperTypes.bool_value:type_name -> google.protobuf.BoolValue
	20, // 15: WrapperTypes.string_value:type_name -> google.protobuf.StringValue
	21, // 16: WrapperTypes.bytes_value:type_name -> google.protobuf.BytesValue
	1,  // 17: AllTypes.scalars:type_name -> ScalarTypes
	3,  // 18: AllTypes.complex:type_name -> ComplexTypes
	4,  // 19: AllTypes.special:type_name -> SpecialTypes
	5,  // 20: AllTypes.wrappers:type_name -> WrapperTypes
	2,  // 21: ComplexTypes.MapMessageEntry.value:type_name -> InnerMessage
	6,  // 22: TypesService.TestAllTypes:input_type -> AllTypes
	6,  // 23: TypesService.TestAllTypes:output_type -> AllTypes
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_types_proto_init() }
func file_proto_types_proto_init() {
	if File_proto_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_types_proto_goTypes,
		DependencyIndexes: file_proto_types_proto_depIdxs,
		EnumInfos:         file_proto_types_proto_enumTypes,
		MessageInfos:      file_proto_types_proto_msgTypes,
	}.Build()
	File_proto_types_proto = out.File
	file_proto_types_proto_goTypes = nil
	file_proto_types_proto_depIdxs = nil
}
