// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/types.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TypesService_TestAllTypes_FullMethodName = "/TypesService/TestAllTypes"
)

// TypesServiceClient is the client API for TypesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type TypesServiceClient interface {
	TestAllTypes(ctx context.Context, in *AllTypes, opts ...grpc.CallOption) (*AllTypes, error)
}

type typesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypesServiceClient(cc grpc.ClientConnInterface) TypesServiceClient {
	return &typesServiceClient{cc}
}

func (c *typesServiceClient) TestAllTypes(ctx context.Context, in *AllTypes, opts ...grpc.CallOption) (*AllTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllTypes)
	err := c.cc.Invoke(ctx, TypesService_TestAllTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypesServiceServer is the server API for TypesService service.
// All implementations must embed UnimplementedTypesServiceServer
// for forward compatibility.
//
// 服务定义
type TypesServiceServer interface {
	TestAllTypes(context.Context, *AllTypes) (*AllTypes, error)
	mustEmbedUnimplementedTypesServiceServer()
}

// UnimplementedTypesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTypesServiceServer struct{}

func (UnimplementedTypesServiceServer) TestAllTypes(context.Context, *AllTypes) (*AllTypes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAllTypes not implemented")
}
func (UnimplementedTypesServiceServer) mustEmbedUnimplementedTypesServiceServer() {}
func (UnimplementedTypesServiceServer) testEmbeddedByValue()                      {}

// UnsafeTypesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypesServiceServer will
// result in compilation errors.
type UnsafeTypesServiceServer interface {
	mustEmbedUnimplementedTypesServiceServer()
}

func RegisterTypesServiceServer(s grpc.ServiceRegistrar, srv TypesServiceServer) {
	// If the following call pancis, it indicates UnimplementedTypesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TypesService_ServiceDesc, srv)
}

func _TypesService_TestAllTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllTypes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesServiceServer).TestAllTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypesService_TestAllTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesServiceServer).TestAllTypes(ctx, req.(*AllTypes))
	}
	return interceptor(ctx, in, info, handler)
}

// TypesService_ServiceDesc is the grpc.ServiceDesc for TypesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TypesService",
	HandlerType: (*TypesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestAllTypes",
			Handler:    _TypesService_TestAllTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/types.proto",
}
