server:
  name: "user-web"
  env: production
  host: "10.6.64.239"
  tags: [ "user_service" ,"grpc" ]
  port: 8888
  jwtKey: "secret"

database:
  host: localhost
  port: 5432
  user: postgres
  password: secret
  dbname: mydb

logging:
  level: info
  format: json
  output: "logs/app.log"

redis:
  addr: "10.3.1.235:6379"
  password: "Xijingkeji@2024"
  db: 0
  poolSize: 10
  minIdleConns: 5
  maxConnAge: 60000
  idleTimeout: 60000
  maxRetries: 3

consul:
  host: "10.6.64.191"
  port: 8500