server:
  name: "user-service"
  env: production
  port: 8080
  jwtKey: "secret"

database:
  host: localhost
  port: 5432
  user: postgres
  password: secret
  dbname: mydb

logging:
  level: info
  format: json
  output: logs/app.log