name: "user-service"
host: "10.6.64.239"
tags: [ "user_service" ,"grpc" ]

mysql:
  host: "124.222.56.172"
  port: 3306
  db: "gorm"
  user: "tian"
  password: "Tian666~"

consul:
  host: "10.6.64.191"
  port: 8500