// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\westwell\Desktop\tmb\TianGo\Language\go\projects\webook\internal\service\sms\types.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\westwell\Desktop\tmb\TianGo\Language\go\projects\webook\internal\service\sms\types.go -package=smsMock -destination=C:\Users\westwell\Desktop\tmb\TianGo\Language\go\projects\webook\internal\service\sms\types1.go
//

// Package smsMock is a generated GoMock package.
package smsMock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockService) Send(ctx context.Context, tplId string, paramSet []string, number ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tplId, paramSet}
	for _, a := range number {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockServiceMockRecorder) Send(ctx, tplId, paramSet any, number ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tplId, paramSet}, number...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockService)(nil).Send), varargs...)
}
