// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package integration

import (
	"github.com/gin-gonic/gin"
	ioc2 "webook/internal/ioc"
	"webook/internal/repository"
	"webook/internal/repository/cache/code"
	"webook/internal/repository/cache/user"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
	"webook/internal/web/jwt"
)

// Injectors from wire.go:

/**
wire.Build()：声明依赖组装规则，是生成注入代码的核心；
wire.NewSet()：分组管理 Provider，提高代码复用性和可读性；
wire.Bind()：绑定接口与实现，解决面向接口编程的依赖注入问题。
*/
// 依赖注入，控制反转
func InitWebUser() *gin.Engine {
	logger := ioc2.InitLogger()
	cmdable := ioc2.InitRedis(logger)
	jwtJwt := jwt.NewRedisJwt(cmdable, logger)
	v := ioc2.InitMiddlewares(cmdable, jwtJwt, logger)
	db := ioc2.InitDb(logger)
	userDao := dao.NewUserDao(db)
	userCache := user.NewUserRedisCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := code.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc2.InitSMSService(logger)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, jwtJwt, logger)
	oauth2Service := ioc2.InitOAuth2FeiShuService(logger)
	oAuth2FeiShuHandler := web.NewOAuth2FeiShuHandler(oauth2Service, userService, jwtJwt, logger)
	articleDao := dao.NewGormArticleDao(db)
	articleRepository := repository.NewArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := web.NewArticleHandler(articleService, logger)
	engine := ioc2.InitWebServer(v, userHandler, oAuth2FeiShuHandler, articleHandler)
	return engine
}
