// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/ioc"
	"webook/internal/repository"
	"webook/internal/repository/cache/code"
	"webook/internal/repository/cache/user"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
	"webook/internal/web/jwt"
)

// Injectors from wire.go:

/**
wire.Build()：声明依赖组装规则，是生成注入代码的核心；
wire.NewSet()：分组管理 Provider，提高代码复用性和可读性；
wire.Bind()：绑定接口与实现，解决面向接口编程的依赖注入问题。
*/
// 依赖注入，控制反转
func InitWebUser() *gin.Engine {
	cmdable := ioc.InitRedis()
	jwtJwt := jwt.NewRedisJwt(cmdable)
	v := ioc.InitMiddlewares(cmdable, jwtJwt)
	db := ioc.InitDb()
	userDao := dao.NewUserDao(db)
	userCache := user.NewUserRedisCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := code.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, jwtJwt)
	oauth2Service := ioc.InitOAuth2FeiShuService()
	oAuth2FeiShuHandler := web.NewOAuth2FeiShuHandler(oauth2Service, userService, jwtJwt)
	engine := ioc.InitWebServer(v, userHandler, oAuth2FeiShuHandler)
	return engine
}
